language: php
php:
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # ---------------------
  # Install Drush
  # ---------------------
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database drupal;'

before_script:
  # ---------------------
  # Install apache server
  # ---------------------
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - wget https://cdn.rawgit.com/backdrop/backdrop/fe6e16b6114995eed008596aa7c733bc907a8fca/core/misc/travis-ci/vhost.conf -O /tmp/vhost.conf
  - sudo cp -f /tmp/vhost.conf /etc/apache2/sites-available/default

  # ---------------------
  # Variables
  # ---------------------
  - cd ..
  - export VENDOR=`pwd`
  - cd ..
  - export DRUPAL=`pwd`'/drupal-7.x/'

  # ---------------------
  # Download the codebase
  # ---------------------
  - wget https://github.com/drupal/drupal/archive/7.x.zip -O drupal.zip
  - unzip -qq drupal.zip
  - cd $DRUPAL
  - drush si testing --db-url=mysql://root:@localhost/drupal --yes
  - mv $VENDOR/* sites/all/modules/

  # ---------------------
  # Change doc-root
  # ---------------------
  - sudo sed -i -e "s,/var/www,$DRUPAL,g" /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # ---------------------
  # Prepare env for the module
  # ---------------------
  - drush vset --yes file_temporary_path /tmp
  - drush en -y simpletest io
  - drush vset --yes simpletest_verbose FALSE

  # ---------------------
  # No cache data!
  # ---------------------
  - drush cc all

script:
  - drush test-run --dirty --field-labels=0 'IO'  --uri=http://localhost:80

notifications:
  email: false
  hipchat: 76d833fa0b6bae8860f279a0e7dba0@me.Andy
  flowdock: 8e80a6538fa73fda0f7dd60bf2d44356
